language: go
sudo: false
go:
  - 1.9.x
  - 1.8.x
  - 1.7.x
  - tip
  - master
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify
script:
  - go test -v -race ./...
  - go build ./...
  - $GOPATH/bin/goveralls -service=travis-ci
